import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    // ── Base ──────────────────────────────────────────────────────────
    container: {
        flex: 1,
        backgroundColor: "#f8f8f8",
        paddingTop: 50,
        paddingBottom: 30,
    },
    header: {
        alignItems: "center",
        marginBottom: 12,
    },
    mobileTitle: {
        fontSize: 28,
        fontWeight: "700",
        color: "#1a1a1a",
        letterSpacing: -0.5,
    },

    // ── Deck shelf ────────────────────────────────────────────────────
    shelfContainer: {
        marginBottom: 16,
    },
    shelfLabel: {
        fontSize: 11,
        fontWeight: "700",
        color: "#9ca3af",
        letterSpacing: 1,
        textTransform: "uppercase",
        marginBottom: 10,
        paddingHorizontal: 24,
    },
    shelfScrollContent: {
        gap: 12,
        paddingHorizontal: 24,
        paddingBottom: 4,
    },
    deckCard: {
        width: 80,
        height: 112,
        borderRadius: 10,
        justifyContent: "flex-end",
        padding: 8,
        borderWidth: 1.5,
        borderColor: "rgba(0,0,0,0.06)",
    },
    deckCardActive: {
        borderColor: "#1a1a1a",
        borderWidth: 2,
    },
    deckCardCount: {
        fontSize: 9,
        fontWeight: "600",
        color: "rgba(255,255,255,0.6)",
        marginBottom: 2,
    },
    deckCardName: {
        fontSize: 11,
        fontWeight: "700",
        color: "#fff",
        lineHeight: 14,
    },

    // ── Card ──────────────────────────────────────────────────────────
    cardContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 20,
    },
    card: {
        backgroundColor: "#fff",
        borderRadius: 14,
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.06)",
        justifyContent: "center",
        alignItems: "center",
        padding: 30,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
        elevation: 2,
    },
    promptText: {
        fontSize: 52,
        fontWeight: "700",
        color: "#1a1a1a",
        textAlign: "center",
    },
    mobileCounter: {
        position: "absolute",
        bottom: 16,
        fontSize: 12,
        color: "#9ca3af",
        fontWeight: "600",
    },

    // ── Controls ──────────────────────────────────────────────────────
    mobileControlsRow: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 10,
        paddingHorizontal: 20,
        marginTop: 16,
    },
    mobileNavButton: {
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.06)",
        paddingVertical: 10,
        paddingHorizontal: 24,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    mobileNavButtonText: {
        color: "#1a1a1a",
        fontSize: 20,
        fontWeight: "600",
    },
    shuffleButton: {
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.08)",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
    },
    resetButton: {
        backgroundColor: "#1a1a1a",
        borderColor: "#1a1a1a",
    },
    shuffleButtonText: {
        color: "#6b7280",
        fontSize: 12,
        fontWeight: "600",
        letterSpacing: 0.3,
    },
    resetButtonText: {
        color: "#fff",
    },

    // ── Landscape (mobile) ────────────────────────────────────────────
    landscapeContainer: {
        flex: 1,
        flexDirection: "row",
        backgroundColor: "#f8f8f8",
        alignItems: "center",
    },
    landscapeButton: {
        flex: 0.15,
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#ededf0",
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.06)",
    },
    landscapeButtonText: {
        color: "#1a1a1a",
        fontSize: 48,
        fontWeight: "600",
    },
    landscapeCard: {
        flex: 0.7,
        backgroundColor: "#fff",
        margin: 20,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.08)",
        justifyContent: "center",
        alignItems: "center",
        padding: 40,
        height: "95%",
    },
    landscapePromptText: {
        fontSize: 80,
        fontWeight: "700",
        color: "#1a1a1a",
        textAlign: "center",
    },
    landscapeCounter: {
        position: "absolute",
        bottom: 20,
        fontSize: 14,
        color: "#9ca3af",
        fontWeight: "600",
    },

    // ── Desktop ───────────────────────────────────────────────────────
    desktopContainer: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#f8f8f8",
        height: "100%",
        paddingTop: 40,
        paddingBottom: 20,
    },
    desktopHeader: {
        alignItems: "center",
        marginBottom: 12,
    },
    desktopTitle: {
        fontSize: 32,
        fontWeight: "700",
        color: "#1a1a1a",
        letterSpacing: -0.5,
    },
    desktopLinkText: {
        fontSize: 12,
        color: "#9ca3af",
        marginTop: 4,
    },
    desktopCard: {
        display: "flex",
        backgroundColor: "#fff",
        borderRadius: 14,
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.06)",
        justifyContent: "center",
        alignItems: "center",
        padding: 30,
        width: 560,
        height: 280,
        marginVertical: 14,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 6,
        elevation: 2,
    },
    desktopPromptText: {
        fontSize: 64,
        fontWeight: "700",
        color: "#1a1a1a",
        textAlign: "center",
    },
    desktopControlsRow: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        marginTop: 8,
    },
    desktopNavButton: {
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.08)",
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 22,
    },
    desktopNavButtonText: {
        color: "#1a1a1a",
        fontSize: 20,
        fontWeight: "600",
    },
    desktopShuffleButton: {
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.08)",
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
    },
});
