import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#1a1a2e",
        paddingTop: 60,
        paddingBottom: 40,
    },
    header: {
        alignItems: "center",
        marginBottom: 20,
    },
    title: {
        fontSize: 36,
        fontWeight: "bold",
        color: "#fff",
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 16,
        color: "#aaa",
    },
    dropdownContainer: {
        position: "relative",
        paddingHorizontal: 20,
        marginBottom: 20,
        zIndex: 1000,
    },
    dropdownButton: {
        backgroundColor: "#16213e",
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "#0f3460",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    dropdownButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
        flex: 1,
    },
    dropdownArrow: {
        color: "#fff",
        fontSize: 14,
        marginLeft: 10,
    },
    dropdownMenu: {
        position: "fixed",
        backgroundColor: "#16213e",
        borderRadius: 10,
        marginTop: 60,
        borderWidth: 2,
        borderColor: "#0f3460",
        maxHeight: 300,
    },
    dropdownItem: {
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: "#0f3460",
    },
    dropdownItemActive: {
        backgroundColor: "#0f3460",
    },
    dropdownItemText: {
        color: "#aaa",
        fontSize: 16,
        fontWeight: "500",
    },
    dropdownItemTextActive: {
        color: "#fff",
        fontWeight: "600",
    },
    cardContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 20,
    },
    card: {
        backgroundColor: "#fff",
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
        padding: 30,
    },
    promptText: {
        fontSize: 64,
        fontWeight: "bold",
        color: "#1a1a2e",
        textAlign: "center",
    },
    controls: {
        flexDirection: "row",
        justifyContent: "space-around",
        paddingHorizontal: 20,
        marginTop: 30,
    },
    button: {
        backgroundColor: "#0f3460",
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 10,
        minWidth: 140,
    },
    buttonText: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "600",
        textAlign: "center",
    },
    bottomControls: {
        alignItems: "center",
        marginTop: 20,
    },
    shuffleButton: {
        backgroundColor: "#16213e",
        paddingVertical: 12,
        paddingHorizontal: 25,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "#0f3460",
    },
    resetButton: {
        backgroundColor: "#533483",
        borderColor: "#6a4c93",
    },
    shuffleButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
    },
    // Landscape styles
    landscapeContainer: {
        flex: 1,
        flexDirection: "row",
        backgroundColor: "#1a1a2e",
        alignItems: "center",
    },
    landscapeButton: {
        flex: 0.15,
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#0f3460",
    },
    landscapeButtonText: {
        color: "#fff",
        fontSize: 72,
        fontWeight: "bold",
    },
    landscapeCard: {
        flex: 0.7,
        backgroundColor: "#fff",
        margin: 20,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
        padding: 40,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
        height: "95%",
    },
    landscapePromptText: {
        fontSize: 100,
        fontWeight: "bold",
        color: "#1a1a2e",
        textAlign: "center",
    },
    landscapeCounter: {
        position: "absolute",
        bottom: 20,
        fontSize: 18,
        color: "#666",
        fontWeight: "600",
    },
    // Desktop styles
    desktopContainer: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#1a1a2e",
        height: "100%",
    },
    desktopCard: {
        display: "flex",
        backgroundColor: "#fff",
        margin: 20,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
        padding: 40,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 10,
        },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
        height: "95%",
    },
    desktopRow: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
    },
    desktopButton: {
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#0f3460",
        borderRadius: 20,
        padding: 20,
    },
    desktopButtonText: {
        color: "#fff",
        fontSize: 72,
        fontWeight: "bold",
    },
    desktopShuffleButton: {
        backgroundColor: "#16213e",
        paddingVertical: 12,
        paddingHorizontal: 25,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "#0f3460",
        marginTop: 20,
    },
    linkText: {
        fontSize: 16,
        color: "#aaa",
        marginTop: 10,
    },
});
